// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IdentificationResponse.proto

package OpenFinger;

public final class IdentificationResponseOuterClass {
  private IdentificationResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IdentificationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OpenFinger.IdentificationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>int32 fingerprint_id = 2;</code>
     * @return The fingerprintId.
     */
    int getFingerprintId();
  }
  /**
   * Protobuf type {@code OpenFinger.IdentificationResponse}
   */
  public static final class IdentificationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OpenFinger.IdentificationResponse)
      IdentificationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IdentificationResponse.newBuilder() to construct.
    private IdentificationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IdentificationResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IdentificationResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IdentificationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 16: {

              fingerprintId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OpenFinger.IdentificationResponseOuterClass.internal_static_OpenFinger_IdentificationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OpenFinger.IdentificationResponseOuterClass.internal_static_OpenFinger_IdentificationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OpenFinger.IdentificationResponseOuterClass.IdentificationResponse.class, OpenFinger.IdentificationResponseOuterClass.IdentificationResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int FINGERPRINT_ID_FIELD_NUMBER = 2;
    private int fingerprintId_;
    /**
     * <code>int32 fingerprint_id = 2;</code>
     * @return The fingerprintId.
     */
    @java.lang.Override
    public int getFingerprintId() {
      return fingerprintId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (fingerprintId_ != 0) {
        output.writeInt32(2, fingerprintId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (fingerprintId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, fingerprintId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OpenFinger.IdentificationResponseOuterClass.IdentificationResponse)) {
        return super.equals(obj);
      }
      OpenFinger.IdentificationResponseOuterClass.IdentificationResponse other = (OpenFinger.IdentificationResponseOuterClass.IdentificationResponse) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (getFingerprintId()
          != other.getFingerprintId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + FINGERPRINT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFingerprintId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OpenFinger.IdentificationResponseOuterClass.IdentificationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OpenFinger.IdentificationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OpenFinger.IdentificationResponse)
        OpenFinger.IdentificationResponseOuterClass.IdentificationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OpenFinger.IdentificationResponseOuterClass.internal_static_OpenFinger_IdentificationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OpenFinger.IdentificationResponseOuterClass.internal_static_OpenFinger_IdentificationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OpenFinger.IdentificationResponseOuterClass.IdentificationResponse.class, OpenFinger.IdentificationResponseOuterClass.IdentificationResponse.Builder.class);
      }

      // Construct using OpenFinger.IdentificationResponseOuterClass.IdentificationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        fingerprintId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OpenFinger.IdentificationResponseOuterClass.internal_static_OpenFinger_IdentificationResponse_descriptor;
      }

      @java.lang.Override
      public OpenFinger.IdentificationResponseOuterClass.IdentificationResponse getDefaultInstanceForType() {
        return OpenFinger.IdentificationResponseOuterClass.IdentificationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public OpenFinger.IdentificationResponseOuterClass.IdentificationResponse build() {
        OpenFinger.IdentificationResponseOuterClass.IdentificationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public OpenFinger.IdentificationResponseOuterClass.IdentificationResponse buildPartial() {
        OpenFinger.IdentificationResponseOuterClass.IdentificationResponse result = new OpenFinger.IdentificationResponseOuterClass.IdentificationResponse(this);
        result.success_ = success_;
        result.fingerprintId_ = fingerprintId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OpenFinger.IdentificationResponseOuterClass.IdentificationResponse) {
          return mergeFrom((OpenFinger.IdentificationResponseOuterClass.IdentificationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OpenFinger.IdentificationResponseOuterClass.IdentificationResponse other) {
        if (other == OpenFinger.IdentificationResponseOuterClass.IdentificationResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getFingerprintId() != 0) {
          setFingerprintId(other.getFingerprintId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OpenFinger.IdentificationResponseOuterClass.IdentificationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OpenFinger.IdentificationResponseOuterClass.IdentificationResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private int fingerprintId_ ;
      /**
       * <code>int32 fingerprint_id = 2;</code>
       * @return The fingerprintId.
       */
      @java.lang.Override
      public int getFingerprintId() {
        return fingerprintId_;
      }
      /**
       * <code>int32 fingerprint_id = 2;</code>
       * @param value The fingerprintId to set.
       * @return This builder for chaining.
       */
      public Builder setFingerprintId(int value) {
        
        fingerprintId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fingerprint_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFingerprintId() {
        
        fingerprintId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OpenFinger.IdentificationResponse)
    }

    // @@protoc_insertion_point(class_scope:OpenFinger.IdentificationResponse)
    private static final OpenFinger.IdentificationResponseOuterClass.IdentificationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OpenFinger.IdentificationResponseOuterClass.IdentificationResponse();
    }

    public static OpenFinger.IdentificationResponseOuterClass.IdentificationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IdentificationResponse>
        PARSER = new com.google.protobuf.AbstractParser<IdentificationResponse>() {
      @java.lang.Override
      public IdentificationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IdentificationResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IdentificationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IdentificationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public OpenFinger.IdentificationResponseOuterClass.IdentificationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenFinger_IdentificationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenFinger_IdentificationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034IdentificationResponse.proto\022\nOpenFing" +
      "er\"A\n\026IdentificationResponse\022\017\n\007success\030" +
      "\001 \001(\010\022\026\n\016fingerprint_id\030\002 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OpenFinger_IdentificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OpenFinger_IdentificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenFinger_IdentificationResponse_descriptor,
        new java.lang.String[] { "Success", "FingerprintId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
