// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PreprocessingRequest.proto

package OpenFinger;

public final class PreprocessingRequestOuterClass {
  private PreprocessingRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PreprocessingParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OpenFinger.PreprocessingParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * block size for orientation map 
     * and Gabor filter
     * </pre>
     *
     * <code>int32 block_size = 1;</code>
     * @return The blockSize.
     */
    int getBlockSize();

    /**
     * <pre>
     * lambda parameter for Gabor filter 
     * (defines average ridge width)
     * </pre>
     *
     * <code>double gabor_lambda = 2;</code>
     * @return The gaborLambda.
     */
    double getGaborLambda();

    /**
     * <pre>
     * sigma parameter for Gabor filter 
     * (defines filter strength)
     * </pre>
     *
     * <code>double gabor_sigma = 3;</code>
     * @return The gaborSigma.
     */
    double getGaborSigma();
  }
  /**
   * <pre>
   * message specifying preprocessing params
   * </pre>
   *
   * Protobuf type {@code OpenFinger.PreprocessingParams}
   */
  public static final class PreprocessingParams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OpenFinger.PreprocessingParams)
      PreprocessingParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PreprocessingParams.newBuilder() to construct.
    private PreprocessingParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PreprocessingParams() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PreprocessingParams();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PreprocessingParams(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              blockSize_ = input.readInt32();
              break;
            }
            case 17: {

              gaborLambda_ = input.readDouble();
              break;
            }
            case 25: {

              gaborSigma_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OpenFinger.PreprocessingRequestOuterClass.internal_static_OpenFinger_PreprocessingParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OpenFinger.PreprocessingRequestOuterClass.internal_static_OpenFinger_PreprocessingParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.class, OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.Builder.class);
    }

    public static final int BLOCK_SIZE_FIELD_NUMBER = 1;
    private int blockSize_;
    /**
     * <pre>
     * block size for orientation map 
     * and Gabor filter
     * </pre>
     *
     * <code>int32 block_size = 1;</code>
     * @return The blockSize.
     */
    @java.lang.Override
    public int getBlockSize() {
      return blockSize_;
    }

    public static final int GABOR_LAMBDA_FIELD_NUMBER = 2;
    private double gaborLambda_;
    /**
     * <pre>
     * lambda parameter for Gabor filter 
     * (defines average ridge width)
     * </pre>
     *
     * <code>double gabor_lambda = 2;</code>
     * @return The gaborLambda.
     */
    @java.lang.Override
    public double getGaborLambda() {
      return gaborLambda_;
    }

    public static final int GABOR_SIGMA_FIELD_NUMBER = 3;
    private double gaborSigma_;
    /**
     * <pre>
     * sigma parameter for Gabor filter 
     * (defines filter strength)
     * </pre>
     *
     * <code>double gabor_sigma = 3;</code>
     * @return The gaborSigma.
     */
    @java.lang.Override
    public double getGaborSigma() {
      return gaborSigma_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (blockSize_ != 0) {
        output.writeInt32(1, blockSize_);
      }
      if (gaborLambda_ != 0D) {
        output.writeDouble(2, gaborLambda_);
      }
      if (gaborSigma_ != 0D) {
        output.writeDouble(3, gaborSigma_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (blockSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, blockSize_);
      }
      if (gaborLambda_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, gaborLambda_);
      }
      if (gaborSigma_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, gaborSigma_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams)) {
        return super.equals(obj);
      }
      OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams other = (OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams) obj;

      if (getBlockSize()
          != other.getBlockSize()) return false;
      if (java.lang.Double.doubleToLongBits(getGaborLambda())
          != java.lang.Double.doubleToLongBits(
              other.getGaborLambda())) return false;
      if (java.lang.Double.doubleToLongBits(getGaborSigma())
          != java.lang.Double.doubleToLongBits(
              other.getGaborSigma())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCK_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getBlockSize();
      hash = (37 * hash) + GABOR_LAMBDA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getGaborLambda()));
      hash = (37 * hash) + GABOR_SIGMA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getGaborSigma()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * message specifying preprocessing params
     * </pre>
     *
     * Protobuf type {@code OpenFinger.PreprocessingParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OpenFinger.PreprocessingParams)
        OpenFinger.PreprocessingRequestOuterClass.PreprocessingParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OpenFinger.PreprocessingRequestOuterClass.internal_static_OpenFinger_PreprocessingParams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OpenFinger.PreprocessingRequestOuterClass.internal_static_OpenFinger_PreprocessingParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.class, OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.Builder.class);
      }

      // Construct using OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        blockSize_ = 0;

        gaborLambda_ = 0D;

        gaborSigma_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OpenFinger.PreprocessingRequestOuterClass.internal_static_OpenFinger_PreprocessingParams_descriptor;
      }

      @java.lang.Override
      public OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams getDefaultInstanceForType() {
        return OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.getDefaultInstance();
      }

      @java.lang.Override
      public OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams build() {
        OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams buildPartial() {
        OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams result = new OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams(this);
        result.blockSize_ = blockSize_;
        result.gaborLambda_ = gaborLambda_;
        result.gaborSigma_ = gaborSigma_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams) {
          return mergeFrom((OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams other) {
        if (other == OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.getDefaultInstance()) return this;
        if (other.getBlockSize() != 0) {
          setBlockSize(other.getBlockSize());
        }
        if (other.getGaborLambda() != 0D) {
          setGaborLambda(other.getGaborLambda());
        }
        if (other.getGaborSigma() != 0D) {
          setGaborSigma(other.getGaborSigma());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int blockSize_ ;
      /**
       * <pre>
       * block size for orientation map 
       * and Gabor filter
       * </pre>
       *
       * <code>int32 block_size = 1;</code>
       * @return The blockSize.
       */
      @java.lang.Override
      public int getBlockSize() {
        return blockSize_;
      }
      /**
       * <pre>
       * block size for orientation map 
       * and Gabor filter
       * </pre>
       *
       * <code>int32 block_size = 1;</code>
       * @param value The blockSize to set.
       * @return This builder for chaining.
       */
      public Builder setBlockSize(int value) {
        
        blockSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * block size for orientation map 
       * and Gabor filter
       * </pre>
       *
       * <code>int32 block_size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlockSize() {
        
        blockSize_ = 0;
        onChanged();
        return this;
      }

      private double gaborLambda_ ;
      /**
       * <pre>
       * lambda parameter for Gabor filter 
       * (defines average ridge width)
       * </pre>
       *
       * <code>double gabor_lambda = 2;</code>
       * @return The gaborLambda.
       */
      @java.lang.Override
      public double getGaborLambda() {
        return gaborLambda_;
      }
      /**
       * <pre>
       * lambda parameter for Gabor filter 
       * (defines average ridge width)
       * </pre>
       *
       * <code>double gabor_lambda = 2;</code>
       * @param value The gaborLambda to set.
       * @return This builder for chaining.
       */
      public Builder setGaborLambda(double value) {
        
        gaborLambda_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * lambda parameter for Gabor filter 
       * (defines average ridge width)
       * </pre>
       *
       * <code>double gabor_lambda = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGaborLambda() {
        
        gaborLambda_ = 0D;
        onChanged();
        return this;
      }

      private double gaborSigma_ ;
      /**
       * <pre>
       * sigma parameter for Gabor filter 
       * (defines filter strength)
       * </pre>
       *
       * <code>double gabor_sigma = 3;</code>
       * @return The gaborSigma.
       */
      @java.lang.Override
      public double getGaborSigma() {
        return gaborSigma_;
      }
      /**
       * <pre>
       * sigma parameter for Gabor filter 
       * (defines filter strength)
       * </pre>
       *
       * <code>double gabor_sigma = 3;</code>
       * @param value The gaborSigma to set.
       * @return This builder for chaining.
       */
      public Builder setGaborSigma(double value) {
        
        gaborSigma_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * sigma parameter for Gabor filter 
       * (defines filter strength)
       * </pre>
       *
       * <code>double gabor_sigma = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGaborSigma() {
        
        gaborSigma_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OpenFinger.PreprocessingParams)
    }

    // @@protoc_insertion_point(class_scope:OpenFinger.PreprocessingParams)
    private static final OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams();
    }

    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PreprocessingParams>
        PARSER = new com.google.protobuf.AbstractParser<PreprocessingParams>() {
      @java.lang.Override
      public PreprocessingParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PreprocessingParams(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PreprocessingParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PreprocessingParams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PreprocessingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OpenFinger.PreprocessingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
     * @return Whether the fingerprint field is set.
     */
    boolean hasFingerprint();
    /**
     * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
     * @return The fingerprint.
     */
    OpenFinger.FingerprintOuterClass.Fingerprint getFingerprint();
    /**
     * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
     */
    OpenFinger.FingerprintOuterClass.FingerprintOrBuilder getFingerprintOrBuilder();

    /**
     * <code>.OpenFinger.PreprocessingParams params = 2;</code>
     * @return Whether the params field is set.
     */
    boolean hasParams();
    /**
     * <code>.OpenFinger.PreprocessingParams params = 2;</code>
     * @return The params.
     */
    OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams getParams();
    /**
     * <code>.OpenFinger.PreprocessingParams params = 2;</code>
     */
    OpenFinger.PreprocessingRequestOuterClass.PreprocessingParamsOrBuilder getParamsOrBuilder();
  }
  /**
   * <pre>
   * message specifying preprocessing OpenFinger request
   * </pre>
   *
   * Protobuf type {@code OpenFinger.PreprocessingRequest}
   */
  public static final class PreprocessingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OpenFinger.PreprocessingRequest)
      PreprocessingRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PreprocessingRequest.newBuilder() to construct.
    private PreprocessingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PreprocessingRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PreprocessingRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PreprocessingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              OpenFinger.FingerprintOuterClass.Fingerprint.Builder subBuilder = null;
              if (fingerprint_ != null) {
                subBuilder = fingerprint_.toBuilder();
              }
              fingerprint_ = input.readMessage(OpenFinger.FingerprintOuterClass.Fingerprint.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fingerprint_);
                fingerprint_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.Builder subBuilder = null;
              if (params_ != null) {
                subBuilder = params_.toBuilder();
              }
              params_ = input.readMessage(OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(params_);
                params_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OpenFinger.PreprocessingRequestOuterClass.internal_static_OpenFinger_PreprocessingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OpenFinger.PreprocessingRequestOuterClass.internal_static_OpenFinger_PreprocessingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest.class, OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest.Builder.class);
    }

    public static final int FINGERPRINT_FIELD_NUMBER = 1;
    private OpenFinger.FingerprintOuterClass.Fingerprint fingerprint_;
    /**
     * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
     * @return Whether the fingerprint field is set.
     */
    @java.lang.Override
    public boolean hasFingerprint() {
      return fingerprint_ != null;
    }
    /**
     * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
     * @return The fingerprint.
     */
    @java.lang.Override
    public OpenFinger.FingerprintOuterClass.Fingerprint getFingerprint() {
      return fingerprint_ == null ? OpenFinger.FingerprintOuterClass.Fingerprint.getDefaultInstance() : fingerprint_;
    }
    /**
     * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
     */
    @java.lang.Override
    public OpenFinger.FingerprintOuterClass.FingerprintOrBuilder getFingerprintOrBuilder() {
      return getFingerprint();
    }

    public static final int PARAMS_FIELD_NUMBER = 2;
    private OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams params_;
    /**
     * <code>.OpenFinger.PreprocessingParams params = 2;</code>
     * @return Whether the params field is set.
     */
    @java.lang.Override
    public boolean hasParams() {
      return params_ != null;
    }
    /**
     * <code>.OpenFinger.PreprocessingParams params = 2;</code>
     * @return The params.
     */
    @java.lang.Override
    public OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams getParams() {
      return params_ == null ? OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.getDefaultInstance() : params_;
    }
    /**
     * <code>.OpenFinger.PreprocessingParams params = 2;</code>
     */
    @java.lang.Override
    public OpenFinger.PreprocessingRequestOuterClass.PreprocessingParamsOrBuilder getParamsOrBuilder() {
      return getParams();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fingerprint_ != null) {
        output.writeMessage(1, getFingerprint());
      }
      if (params_ != null) {
        output.writeMessage(2, getParams());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fingerprint_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFingerprint());
      }
      if (params_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getParams());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest)) {
        return super.equals(obj);
      }
      OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest other = (OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest) obj;

      if (hasFingerprint() != other.hasFingerprint()) return false;
      if (hasFingerprint()) {
        if (!getFingerprint()
            .equals(other.getFingerprint())) return false;
      }
      if (hasParams() != other.hasParams()) return false;
      if (hasParams()) {
        if (!getParams()
            .equals(other.getParams())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFingerprint()) {
        hash = (37 * hash) + FINGERPRINT_FIELD_NUMBER;
        hash = (53 * hash) + getFingerprint().hashCode();
      }
      if (hasParams()) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParams().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * message specifying preprocessing OpenFinger request
     * </pre>
     *
     * Protobuf type {@code OpenFinger.PreprocessingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OpenFinger.PreprocessingRequest)
        OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OpenFinger.PreprocessingRequestOuterClass.internal_static_OpenFinger_PreprocessingRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OpenFinger.PreprocessingRequestOuterClass.internal_static_OpenFinger_PreprocessingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest.class, OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest.Builder.class);
      }

      // Construct using OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fingerprintBuilder_ == null) {
          fingerprint_ = null;
        } else {
          fingerprint_ = null;
          fingerprintBuilder_ = null;
        }
        if (paramsBuilder_ == null) {
          params_ = null;
        } else {
          params_ = null;
          paramsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OpenFinger.PreprocessingRequestOuterClass.internal_static_OpenFinger_PreprocessingRequest_descriptor;
      }

      @java.lang.Override
      public OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest getDefaultInstanceForType() {
        return OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest.getDefaultInstance();
      }

      @java.lang.Override
      public OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest build() {
        OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest buildPartial() {
        OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest result = new OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest(this);
        if (fingerprintBuilder_ == null) {
          result.fingerprint_ = fingerprint_;
        } else {
          result.fingerprint_ = fingerprintBuilder_.build();
        }
        if (paramsBuilder_ == null) {
          result.params_ = params_;
        } else {
          result.params_ = paramsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest) {
          return mergeFrom((OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest other) {
        if (other == OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest.getDefaultInstance()) return this;
        if (other.hasFingerprint()) {
          mergeFingerprint(other.getFingerprint());
        }
        if (other.hasParams()) {
          mergeParams(other.getParams());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private OpenFinger.FingerprintOuterClass.Fingerprint fingerprint_;
      private com.google.protobuf.SingleFieldBuilderV3<
          OpenFinger.FingerprintOuterClass.Fingerprint, OpenFinger.FingerprintOuterClass.Fingerprint.Builder, OpenFinger.FingerprintOuterClass.FingerprintOrBuilder> fingerprintBuilder_;
      /**
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       * @return Whether the fingerprint field is set.
       */
      public boolean hasFingerprint() {
        return fingerprintBuilder_ != null || fingerprint_ != null;
      }
      /**
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       * @return The fingerprint.
       */
      public OpenFinger.FingerprintOuterClass.Fingerprint getFingerprint() {
        if (fingerprintBuilder_ == null) {
          return fingerprint_ == null ? OpenFinger.FingerprintOuterClass.Fingerprint.getDefaultInstance() : fingerprint_;
        } else {
          return fingerprintBuilder_.getMessage();
        }
      }
      /**
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      public Builder setFingerprint(OpenFinger.FingerprintOuterClass.Fingerprint value) {
        if (fingerprintBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fingerprint_ = value;
          onChanged();
        } else {
          fingerprintBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      public Builder setFingerprint(
          OpenFinger.FingerprintOuterClass.Fingerprint.Builder builderForValue) {
        if (fingerprintBuilder_ == null) {
          fingerprint_ = builderForValue.build();
          onChanged();
        } else {
          fingerprintBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      public Builder mergeFingerprint(OpenFinger.FingerprintOuterClass.Fingerprint value) {
        if (fingerprintBuilder_ == null) {
          if (fingerprint_ != null) {
            fingerprint_ =
              OpenFinger.FingerprintOuterClass.Fingerprint.newBuilder(fingerprint_).mergeFrom(value).buildPartial();
          } else {
            fingerprint_ = value;
          }
          onChanged();
        } else {
          fingerprintBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      public Builder clearFingerprint() {
        if (fingerprintBuilder_ == null) {
          fingerprint_ = null;
          onChanged();
        } else {
          fingerprint_ = null;
          fingerprintBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      public OpenFinger.FingerprintOuterClass.Fingerprint.Builder getFingerprintBuilder() {
        
        onChanged();
        return getFingerprintFieldBuilder().getBuilder();
      }
      /**
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      public OpenFinger.FingerprintOuterClass.FingerprintOrBuilder getFingerprintOrBuilder() {
        if (fingerprintBuilder_ != null) {
          return fingerprintBuilder_.getMessageOrBuilder();
        } else {
          return fingerprint_ == null ?
              OpenFinger.FingerprintOuterClass.Fingerprint.getDefaultInstance() : fingerprint_;
        }
      }
      /**
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          OpenFinger.FingerprintOuterClass.Fingerprint, OpenFinger.FingerprintOuterClass.Fingerprint.Builder, OpenFinger.FingerprintOuterClass.FingerprintOrBuilder> 
          getFingerprintFieldBuilder() {
        if (fingerprintBuilder_ == null) {
          fingerprintBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              OpenFinger.FingerprintOuterClass.Fingerprint, OpenFinger.FingerprintOuterClass.Fingerprint.Builder, OpenFinger.FingerprintOuterClass.FingerprintOrBuilder>(
                  getFingerprint(),
                  getParentForChildren(),
                  isClean());
          fingerprint_ = null;
        }
        return fingerprintBuilder_;
      }

      private OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams params_;
      private com.google.protobuf.SingleFieldBuilderV3<
          OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams, OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.Builder, OpenFinger.PreprocessingRequestOuterClass.PreprocessingParamsOrBuilder> paramsBuilder_;
      /**
       * <code>.OpenFinger.PreprocessingParams params = 2;</code>
       * @return Whether the params field is set.
       */
      public boolean hasParams() {
        return paramsBuilder_ != null || params_ != null;
      }
      /**
       * <code>.OpenFinger.PreprocessingParams params = 2;</code>
       * @return The params.
       */
      public OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams getParams() {
        if (paramsBuilder_ == null) {
          return params_ == null ? OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.getDefaultInstance() : params_;
        } else {
          return paramsBuilder_.getMessage();
        }
      }
      /**
       * <code>.OpenFinger.PreprocessingParams params = 2;</code>
       */
      public Builder setParams(OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          params_ = value;
          onChanged();
        } else {
          paramsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.OpenFinger.PreprocessingParams params = 2;</code>
       */
      public Builder setParams(
          OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          params_ = builderForValue.build();
          onChanged();
        } else {
          paramsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.OpenFinger.PreprocessingParams params = 2;</code>
       */
      public Builder mergeParams(OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams value) {
        if (paramsBuilder_ == null) {
          if (params_ != null) {
            params_ =
              OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.newBuilder(params_).mergeFrom(value).buildPartial();
          } else {
            params_ = value;
          }
          onChanged();
        } else {
          paramsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.OpenFinger.PreprocessingParams params = 2;</code>
       */
      public Builder clearParams() {
        if (paramsBuilder_ == null) {
          params_ = null;
          onChanged();
        } else {
          params_ = null;
          paramsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.OpenFinger.PreprocessingParams params = 2;</code>
       */
      public OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.Builder getParamsBuilder() {
        
        onChanged();
        return getParamsFieldBuilder().getBuilder();
      }
      /**
       * <code>.OpenFinger.PreprocessingParams params = 2;</code>
       */
      public OpenFinger.PreprocessingRequestOuterClass.PreprocessingParamsOrBuilder getParamsOrBuilder() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilder();
        } else {
          return params_ == null ?
              OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.getDefaultInstance() : params_;
        }
      }
      /**
       * <code>.OpenFinger.PreprocessingParams params = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams, OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.Builder, OpenFinger.PreprocessingRequestOuterClass.PreprocessingParamsOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams, OpenFinger.PreprocessingRequestOuterClass.PreprocessingParams.Builder, OpenFinger.PreprocessingRequestOuterClass.PreprocessingParamsOrBuilder>(
                  getParams(),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OpenFinger.PreprocessingRequest)
    }

    // @@protoc_insertion_point(class_scope:OpenFinger.PreprocessingRequest)
    private static final OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest();
    }

    public static OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PreprocessingRequest>
        PARSER = new com.google.protobuf.AbstractParser<PreprocessingRequest>() {
      @java.lang.Override
      public PreprocessingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PreprocessingRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PreprocessingRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PreprocessingRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public OpenFinger.PreprocessingRequestOuterClass.PreprocessingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenFinger_PreprocessingParams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenFinger_PreprocessingParams_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenFinger_PreprocessingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenFinger_PreprocessingRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032PreprocessingRequest.proto\022\nOpenFinger" +
      "\032\021Fingerprint.proto\"T\n\023PreprocessingPara" +
      "ms\022\022\n\nblock_size\030\001 \001(\005\022\024\n\014gabor_lambda\030\002" +
      " \001(\001\022\023\n\013gabor_sigma\030\003 \001(\001\"u\n\024Preprocessi" +
      "ngRequest\022,\n\013fingerprint\030\001 \001(\0132\027.OpenFin" +
      "ger.Fingerprint\022/\n\006params\030\002 \001(\0132\037.OpenFi" +
      "nger.PreprocessingParamsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          OpenFinger.FingerprintOuterClass.getDescriptor(),
        });
    internal_static_OpenFinger_PreprocessingParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OpenFinger_PreprocessingParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenFinger_PreprocessingParams_descriptor,
        new java.lang.String[] { "BlockSize", "GaborLambda", "GaborSigma", });
    internal_static_OpenFinger_PreprocessingRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OpenFinger_PreprocessingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenFinger_PreprocessingRequest_descriptor,
        new java.lang.String[] { "Fingerprint", "Params", });
    OpenFinger.FingerprintOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
