// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegistrationResponse.proto

package OpenFinger;

public final class RegistrationResponseOuterClass {
  private RegistrationResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RegistrationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OpenFinger.RegistrationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 requestId = 1;</code>
     * @return The requestId.
     */
    int getRequestId();

    /**
     * <code>string registration_status = 2;</code>
     * @return The registrationStatus.
     */
    java.lang.String getRegistrationStatus();
    /**
     * <code>string registration_status = 2;</code>
     * @return The bytes for registrationStatus.
     */
    com.google.protobuf.ByteString
        getRegistrationStatusBytes();
  }
  /**
   * Protobuf type {@code OpenFinger.RegistrationResponse}
   */
  public static final class RegistrationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OpenFinger.RegistrationResponse)
      RegistrationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegistrationResponse.newBuilder() to construct.
    private RegistrationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegistrationResponse() {
      registrationStatus_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RegistrationResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegistrationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              requestId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              registrationStatus_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OpenFinger.RegistrationResponseOuterClass.internal_static_OpenFinger_RegistrationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OpenFinger.RegistrationResponseOuterClass.internal_static_OpenFinger_RegistrationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OpenFinger.RegistrationResponseOuterClass.RegistrationResponse.class, OpenFinger.RegistrationResponseOuterClass.RegistrationResponse.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private int requestId_;
    /**
     * <code>int32 requestId = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public int getRequestId() {
      return requestId_;
    }

    public static final int REGISTRATION_STATUS_FIELD_NUMBER = 2;
    private volatile java.lang.Object registrationStatus_;
    /**
     * <code>string registration_status = 2;</code>
     * @return The registrationStatus.
     */
    @java.lang.Override
    public java.lang.String getRegistrationStatus() {
      java.lang.Object ref = registrationStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        registrationStatus_ = s;
        return s;
      }
    }
    /**
     * <code>string registration_status = 2;</code>
     * @return The bytes for registrationStatus.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRegistrationStatusBytes() {
      java.lang.Object ref = registrationStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        registrationStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0) {
        output.writeInt32(1, requestId_);
      }
      if (!getRegistrationStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, registrationStatus_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, requestId_);
      }
      if (!getRegistrationStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, registrationStatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OpenFinger.RegistrationResponseOuterClass.RegistrationResponse)) {
        return super.equals(obj);
      }
      OpenFinger.RegistrationResponseOuterClass.RegistrationResponse other = (OpenFinger.RegistrationResponseOuterClass.RegistrationResponse) obj;

      if (getRequestId()
          != other.getRequestId()) return false;
      if (!getRegistrationStatus()
          .equals(other.getRegistrationStatus())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId();
      hash = (37 * hash) + REGISTRATION_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getRegistrationStatus().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OpenFinger.RegistrationResponseOuterClass.RegistrationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OpenFinger.RegistrationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OpenFinger.RegistrationResponse)
        OpenFinger.RegistrationResponseOuterClass.RegistrationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OpenFinger.RegistrationResponseOuterClass.internal_static_OpenFinger_RegistrationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OpenFinger.RegistrationResponseOuterClass.internal_static_OpenFinger_RegistrationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OpenFinger.RegistrationResponseOuterClass.RegistrationResponse.class, OpenFinger.RegistrationResponseOuterClass.RegistrationResponse.Builder.class);
      }

      // Construct using OpenFinger.RegistrationResponseOuterClass.RegistrationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = 0;

        registrationStatus_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OpenFinger.RegistrationResponseOuterClass.internal_static_OpenFinger_RegistrationResponse_descriptor;
      }

      @java.lang.Override
      public OpenFinger.RegistrationResponseOuterClass.RegistrationResponse getDefaultInstanceForType() {
        return OpenFinger.RegistrationResponseOuterClass.RegistrationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public OpenFinger.RegistrationResponseOuterClass.RegistrationResponse build() {
        OpenFinger.RegistrationResponseOuterClass.RegistrationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public OpenFinger.RegistrationResponseOuterClass.RegistrationResponse buildPartial() {
        OpenFinger.RegistrationResponseOuterClass.RegistrationResponse result = new OpenFinger.RegistrationResponseOuterClass.RegistrationResponse(this);
        result.requestId_ = requestId_;
        result.registrationStatus_ = registrationStatus_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OpenFinger.RegistrationResponseOuterClass.RegistrationResponse) {
          return mergeFrom((OpenFinger.RegistrationResponseOuterClass.RegistrationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OpenFinger.RegistrationResponseOuterClass.RegistrationResponse other) {
        if (other == OpenFinger.RegistrationResponseOuterClass.RegistrationResponse.getDefaultInstance()) return this;
        if (other.getRequestId() != 0) {
          setRequestId(other.getRequestId());
        }
        if (!other.getRegistrationStatus().isEmpty()) {
          registrationStatus_ = other.registrationStatus_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OpenFinger.RegistrationResponseOuterClass.RegistrationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OpenFinger.RegistrationResponseOuterClass.RegistrationResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int requestId_ ;
      /**
       * <code>int32 requestId = 1;</code>
       * @return The requestId.
       */
      @java.lang.Override
      public int getRequestId() {
        return requestId_;
      }
      /**
       * <code>int32 requestId = 1;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(int value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 requestId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        
        requestId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object registrationStatus_ = "";
      /**
       * <code>string registration_status = 2;</code>
       * @return The registrationStatus.
       */
      public java.lang.String getRegistrationStatus() {
        java.lang.Object ref = registrationStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          registrationStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string registration_status = 2;</code>
       * @return The bytes for registrationStatus.
       */
      public com.google.protobuf.ByteString
          getRegistrationStatusBytes() {
        java.lang.Object ref = registrationStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          registrationStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string registration_status = 2;</code>
       * @param value The registrationStatus to set.
       * @return This builder for chaining.
       */
      public Builder setRegistrationStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        registrationStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string registration_status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegistrationStatus() {
        
        registrationStatus_ = getDefaultInstance().getRegistrationStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string registration_status = 2;</code>
       * @param value The bytes for registrationStatus to set.
       * @return This builder for chaining.
       */
      public Builder setRegistrationStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        registrationStatus_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OpenFinger.RegistrationResponse)
    }

    // @@protoc_insertion_point(class_scope:OpenFinger.RegistrationResponse)
    private static final OpenFinger.RegistrationResponseOuterClass.RegistrationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OpenFinger.RegistrationResponseOuterClass.RegistrationResponse();
    }

    public static OpenFinger.RegistrationResponseOuterClass.RegistrationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegistrationResponse>
        PARSER = new com.google.protobuf.AbstractParser<RegistrationResponse>() {
      @java.lang.Override
      public RegistrationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegistrationResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegistrationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegistrationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public OpenFinger.RegistrationResponseOuterClass.RegistrationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenFinger_RegistrationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenFinger_RegistrationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032RegistrationResponse.proto\022\nOpenFinger" +
      "\"F\n\024RegistrationResponse\022\021\n\trequestId\030\001 " +
      "\001(\005\022\033\n\023registration_status\030\002 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OpenFinger_RegistrationResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OpenFinger_RegistrationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenFinger_RegistrationResponse_descriptor,
        new java.lang.String[] { "RequestId", "RegistrationStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
