// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VerificationResponseOlejarnikova.proto

package OpenFinger;

public final class VerificationResponseOlejarnikovaOuterClass {
  private VerificationResponseOlejarnikovaOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VerificationResponseOlejarnikovaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OpenFinger.VerificationResponseOlejarnikova)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 requestId = 1;</code>
     * @return The requestId.
     */
    int getRequestId();

    /**
     * <code>bool success = 2;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>float score = 3;</code>
     * @return The score.
     */
    float getScore();
  }
  /**
   * Protobuf type {@code OpenFinger.VerificationResponseOlejarnikova}
   */
  public static final class VerificationResponseOlejarnikova extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OpenFinger.VerificationResponseOlejarnikova)
      VerificationResponseOlejarnikovaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VerificationResponseOlejarnikova.newBuilder() to construct.
    private VerificationResponseOlejarnikova(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VerificationResponseOlejarnikova() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VerificationResponseOlejarnikova();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VerificationResponseOlejarnikova(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              requestId_ = input.readInt32();
              break;
            }
            case 16: {

              success_ = input.readBool();
              break;
            }
            case 29: {

              score_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OpenFinger.VerificationResponseOlejarnikovaOuterClass.internal_static_OpenFinger_VerificationResponseOlejarnikova_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OpenFinger.VerificationResponseOlejarnikovaOuterClass.internal_static_OpenFinger_VerificationResponseOlejarnikova_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova.class, OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private int requestId_;
    /**
     * <code>int32 requestId = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public int getRequestId() {
      return requestId_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_;
    /**
     * <code>bool success = 2;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int SCORE_FIELD_NUMBER = 3;
    private float score_;
    /**
     * <code>float score = 3;</code>
     * @return The score.
     */
    @java.lang.Override
    public float getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0) {
        output.writeInt32(1, requestId_);
      }
      if (success_ != false) {
        output.writeBool(2, success_);
      }
      if (score_ != 0F) {
        output.writeFloat(3, score_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, requestId_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, success_);
      }
      if (score_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, score_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova)) {
        return super.equals(obj);
      }
      OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova other = (OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova) obj;

      if (getRequestId()
          != other.getRequestId()) return false;
      if (getSuccess()
          != other.getSuccess()) return false;
      if (java.lang.Float.floatToIntBits(getScore())
          != java.lang.Float.floatToIntBits(
              other.getScore())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getScore());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OpenFinger.VerificationResponseOlejarnikova}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OpenFinger.VerificationResponseOlejarnikova)
        OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikovaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OpenFinger.VerificationResponseOlejarnikovaOuterClass.internal_static_OpenFinger_VerificationResponseOlejarnikova_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OpenFinger.VerificationResponseOlejarnikovaOuterClass.internal_static_OpenFinger_VerificationResponseOlejarnikova_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova.class, OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova.Builder.class);
      }

      // Construct using OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = 0;

        success_ = false;

        score_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OpenFinger.VerificationResponseOlejarnikovaOuterClass.internal_static_OpenFinger_VerificationResponseOlejarnikova_descriptor;
      }

      @java.lang.Override
      public OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova getDefaultInstanceForType() {
        return OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova.getDefaultInstance();
      }

      @java.lang.Override
      public OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova build() {
        OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova buildPartial() {
        OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova result = new OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova(this);
        result.requestId_ = requestId_;
        result.success_ = success_;
        result.score_ = score_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova) {
          return mergeFrom((OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova other) {
        if (other == OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova.getDefaultInstance()) return this;
        if (other.getRequestId() != 0) {
          setRequestId(other.getRequestId());
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getScore() != 0F) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int requestId_ ;
      /**
       * <code>int32 requestId = 1;</code>
       * @return The requestId.
       */
      @java.lang.Override
      public int getRequestId() {
        return requestId_;
      }
      /**
       * <code>int32 requestId = 1;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(int value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 requestId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        
        requestId_ = 0;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 2;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 2;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private float score_ ;
      /**
       * <code>float score = 3;</code>
       * @return The score.
       */
      @java.lang.Override
      public float getScore() {
        return score_;
      }
      /**
       * <code>float score = 3;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(float value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float score = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        
        score_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OpenFinger.VerificationResponseOlejarnikova)
    }

    // @@protoc_insertion_point(class_scope:OpenFinger.VerificationResponseOlejarnikova)
    private static final OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova();
    }

    public static OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VerificationResponseOlejarnikova>
        PARSER = new com.google.protobuf.AbstractParser<VerificationResponseOlejarnikova>() {
      @java.lang.Override
      public VerificationResponseOlejarnikova parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VerificationResponseOlejarnikova(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VerificationResponseOlejarnikova> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VerificationResponseOlejarnikova> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public OpenFinger.VerificationResponseOlejarnikovaOuterClass.VerificationResponseOlejarnikova getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenFinger_VerificationResponseOlejarnikova_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenFinger_VerificationResponseOlejarnikova_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&VerificationResponseOlejarnikova.proto" +
      "\022\nOpenFinger\"U\n VerificationResponseOlej" +
      "arnikova\022\021\n\trequestId\030\001 \001(\005\022\017\n\007success\030\002" +
      " \001(\010\022\r\n\005score\030\003 \001(\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OpenFinger_VerificationResponseOlejarnikova_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OpenFinger_VerificationResponseOlejarnikova_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenFinger_VerificationResponseOlejarnikova_descriptor,
        new java.lang.String[] { "RequestId", "Success", "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
