package message.request;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my.proto

public final class RegistrationRequestProto {
    private RegistrationRequestProto() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface RegistrationRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:RegistrationRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 requestId = 1;</code>
         * @return The requestId.
         */
        int getRequestId();

        /**
         * <code>string login = 2;</code>
         * @return The login.
         */
        java.lang.String getLogin();
        /**
         * <code>string login = 2;</code>
         * @return The bytes for login.
         */
        com.google.protobuf.ByteString
        getLoginBytes();

        /**
         * <code>bytes fingerprint = 3;</code>
         * @return The fingerprint.
         */
        com.google.protobuf.ByteString getFingerprint();
    }
    /**
     * Protobuf type {@code RegistrationRequest}
     */
    public static final class RegistrationRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:RegistrationRequest)
            RegistrationRequestOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use RegistrationRequest.newBuilder() to construct.
        private RegistrationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private RegistrationRequest() {
            login_ = "";
            fingerprint_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new RegistrationRequest();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private RegistrationRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            requestId_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            login_ = s;
                            break;
                        }
                        case 26: {

                            fingerprint_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return RegistrationRequestProto.internal_static_RegistrationRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return RegistrationRequestProto.internal_static_RegistrationRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            RegistrationRequest.class, RegistrationRequest.Builder.class);
        }

        public static final int REQUESTID_FIELD_NUMBER = 1;
        private int requestId_;
        /**
         * <code>int32 requestId = 1;</code>
         * @return The requestId.
         */
        @java.lang.Override
        public int getRequestId() {
            return requestId_;
        }

        public static final int LOGIN_FIELD_NUMBER = 2;
        private volatile java.lang.Object login_;
        /**
         * <code>string login = 2;</code>
         * @return The login.
         */
        @java.lang.Override
        public java.lang.String getLogin() {
            java.lang.Object ref = login_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                login_ = s;
                return s;
            }
        }
        /**
         * <code>string login = 2;</code>
         * @return The bytes for login.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getLoginBytes() {
            java.lang.Object ref = login_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                login_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int FINGERPRINT_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString fingerprint_;
        /**
         * <code>bytes fingerprint = 3;</code>
         * @return The fingerprint.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getFingerprint() {
            return fingerprint_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (requestId_ != 0) {
                output.writeInt32(1, requestId_);
            }
            if (!getLoginBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, login_);
            }
            if (!fingerprint_.isEmpty()) {
                output.writeBytes(3, fingerprint_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (requestId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, requestId_);
            }
            if (!getLoginBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, login_);
            }
            if (!fingerprint_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, fingerprint_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof RegistrationRequest)) {
                return super.equals(obj);
            }
            RegistrationRequest other = (RegistrationRequest) obj;

            if (getRequestId()
                    != other.getRequestId()) return false;
            if (!getLogin()
                    .equals(other.getLogin())) return false;
            if (!getFingerprint()
                    .equals(other.getFingerprint())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
            hash = (53 * hash) + getRequestId();
            hash = (37 * hash) + LOGIN_FIELD_NUMBER;
            hash = (53 * hash) + getLogin().hashCode();
            hash = (37 * hash) + FINGERPRINT_FIELD_NUMBER;
            hash = (53 * hash) + getFingerprint().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static RegistrationRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static RegistrationRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static RegistrationRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static RegistrationRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static RegistrationRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static RegistrationRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static RegistrationRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static RegistrationRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static RegistrationRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static RegistrationRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static RegistrationRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static RegistrationRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(RegistrationRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code RegistrationRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:RegistrationRequest)
                RegistrationRequestProto.RegistrationRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return RegistrationRequestProto.internal_static_RegistrationRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return RegistrationRequestProto.internal_static_RegistrationRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                RegistrationRequest.class, RegistrationRequest.Builder.class);
            }

            // Construct using My.RegistrationRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                requestId_ = 0;

                login_ = "";

                fingerprint_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return RegistrationRequestProto.internal_static_RegistrationRequest_descriptor;
            }

            @java.lang.Override
            public RegistrationRequest getDefaultInstanceForType() {
                return RegistrationRequestProto.RegistrationRequest.getDefaultInstance();
            }

            @java.lang.Override
            public RegistrationRequest build() {
                RegistrationRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public RegistrationRequest buildPartial() {
                RegistrationRequest result = new RegistrationRequest(this);
                result.requestId_ = requestId_;
                result.login_ = login_;
                result.fingerprint_ = fingerprint_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof RegistrationRequest) {
                    return mergeFrom((RegistrationRequest)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(RegistrationRequest other) {
                if (other == RegistrationRequestProto.RegistrationRequest.getDefaultInstance()) return this;
                if (other.getRequestId() != 0) {
                    setRequestId(other.getRequestId());
                }
                if (!other.getLogin().isEmpty()) {
                    login_ = other.login_;
                    onChanged();
                }
                if (other.getFingerprint() != com.google.protobuf.ByteString.EMPTY) {
                    setFingerprint(other.getFingerprint());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                RegistrationRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (RegistrationRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int requestId_ ;
            /**
             * <code>int32 requestId = 1;</code>
             * @return The requestId.
             */
            @java.lang.Override
            public int getRequestId() {
                return requestId_;
            }
            /**
             * <code>int32 requestId = 1;</code>
             * @param value The requestId to set.
             * @return This builder for chaining.
             */
            public Builder setRequestId(int value) {

                requestId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 requestId = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearRequestId() {

                requestId_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object login_ = "";
            /**
             * <code>string login = 2;</code>
             * @return The login.
             */
            public java.lang.String getLogin() {
                java.lang.Object ref = login_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    login_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string login = 2;</code>
             * @return The bytes for login.
             */
            public com.google.protobuf.ByteString
            getLoginBytes() {
                java.lang.Object ref = login_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    login_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string login = 2;</code>
             * @param value The login to set.
             * @return This builder for chaining.
             */
            public Builder setLogin(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                login_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string login = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearLogin() {

                login_ = getDefaultInstance().getLogin();
                onChanged();
                return this;
            }
            /**
             * <code>string login = 2;</code>
             * @param value The bytes for login to set.
             * @return This builder for chaining.
             */
            public Builder setLoginBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                login_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString fingerprint_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes fingerprint = 3;</code>
             * @return The fingerprint.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getFingerprint() {
                return fingerprint_;
            }
            /**
             * <code>bytes fingerprint = 3;</code>
             * @param value The fingerprint to set.
             * @return This builder for chaining.
             */
            public Builder setFingerprint(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                fingerprint_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes fingerprint = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearFingerprint() {

                fingerprint_ = getDefaultInstance().getFingerprint();
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:RegistrationRequest)
        }

        // @@protoc_insertion_point(class_scope:RegistrationRequest)
        private static final RegistrationRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new RegistrationRequest();
        }

        public static RegistrationRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<RegistrationRequest>
                PARSER = new com.google.protobuf.AbstractParser<RegistrationRequest>() {
            @java.lang.Override
            public RegistrationRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new RegistrationRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<RegistrationRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RegistrationRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public RegistrationRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_RegistrationRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_RegistrationRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\010my.proto\"L\n\023RegistrationRequest\022\021\n\treq" +
                        "uestId\030\001 \001(\005\022\r\n\005login\030\002 \001(\t\022\023\n\013fingerpri" +
                        "nt\030\003 \001(\014b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_RegistrationRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_RegistrationRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_RegistrationRequest_descriptor,
                new java.lang.String[] { "RequestId", "Login", "Fingerprint", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
